# https://opensource.zalando.com/postgres-operator/
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"
metadata:
  name: {{ .Values.postgresql.database }}
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: {{ .Values.postgresql.replicas }}

  # enableMasterLoadBalancer: true
  volume:
    size: {{ .Values.postgresql.size }}

  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 2500m
      memory: 3000Mi

  users:
    {{ .Values.postgresql.user }}: []

  databases:
    {{ .Values.postgresql.database }}: {{ .Values.postgresql.user }}
